name: unitastic_mobile
description: A cross-platform mobile application for Unitastic.
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  url_launcher: ^6.1.14
  flutter_native_splash: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/fonts/
  uses-material-design: true

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "assets/images/adaptive_bg.png"
  adaptive_icon_foreground: "assets/images/adaptive_fg.png"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#00adb5"
  image: "assets/images/adaptive_fg.png"
  color_dark: "#00adb5"
  image_dark: "assets/images/adaptive_fg.png"

  android_12:
    image: "assets/images/adaptive_fg.png"
    icon_background_color: "#00adb5"
    image_dark: "assets/images/adaptive_fg.png"
    icon_background_color_dark: "#00adb5"